// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/tatsuo48/go_ddd/application/service"
	"github.com/tatsuo48/go_ddd/infrastructure/repositry"
)

// Injectors from wire.go:

func initUser(fileName string) *service.UserApplicationService {
	iUserRepositry := repositry.NewInMemoryUserRepositry(fileName)
	userApplicationService := service.NewUserApplicationService(iUserRepositry)
	return userApplicationService
}
